export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';

export const ADD_LIKE = 'ADD_LIKE';
export const ADD_DISLIKE = 'ADD_DISLIKE';

export const UPDATE_LIKES = 'UPDATE_LIKES';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const GET_MOVIES_BY_CATEGORIES = 'GET_MOVIES_BY_CATEGORIES';
export const GET_MOVIES_BY_CATEGORIES_SUCCESS = 'GET_MOVIES_BY_CATEGORIES_SUCCESS';
